### PR TITLE
Client side bug fix

### LINKED ISSUE #11: [Bug]: Client side error when viewing a project
### What happened?

When i click to view a project it returns a clients side error. I would like to fix it

### Add screenshots

image

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Bashamega**
## Fixes Issue

fixes #11 

## Check List (Check all the applicable boxes) 

- [x] My Changes follow the Code of Conduct of this Project. 
- [x] My Post or Change does not contain any **Plagarized** Content. 
- [x] The title of the PR is a short description of the Changes made.

### CODE REVIEW

**Comment by Zemerik** [comment]
Hey @Bashamega , 

Unfortunately, your PR does not fix the issue. If you visit the Vercel Preview, you still can't see the project info. 

Screenshot

**Review by Zemerik — CHANGES_REQUESTED** [review]
View the Preview Deployment here - https://zemshowcase-git-fork-bashamega-cl-46ba41-hemang-yadavs-projects.vercel.app/

**Comment by Bashamega** [comment]
Hello @Zemerik.

The link that you gave me requires access which i don't have, and when i ran `npm run build` it didn't return an error. Can you send me more details like the error?
 
image

**Comment by Zemerik** [comment]
Hey @Bashamega , 

Here is the screenshot of the console 👇

image

**Comment by Bashamega** [comment]
It should be fix now. all the check are passing

**Comment by Zemerik** [comment]
Unfortunately, the client side bug is still there and users are not able to view the project. 

image

**Comment by Bashamega** [comment]
> Unfortunately, the client side bug is still there and users are not able to view the project.
> 
> image


Are you sure that you are running the latest deployment?
I have ran it locally and there is no errors

**Comment by Zemerik** [comment]
> > Unfortunately, the client side bug is still there and users are not able to view the project.
> > image
> 
> Are you sure that you are running the latest deployment? I have ran it locally and there is no errors

Hey Adam, 

The Preview that I showed you was the preview of the commit below, which appears to be the latest commit 👇

https://github.com/Zemerik/ZemShowcase/pull/14/commits/f802d19fea2081e028a36c1635d648abd14da526

**Comment by Zemerik** [comment]
@Bashamega , 

Should I merge your this PR and see if it works? That way you can get a better understanding of the problem

**Comment by Bashamega** [comment]
> @Bashamega , 
> 
> Should I merge your this PR and see if it works? That way you can get a better understanding of the problem

Sure

**Pull request merged**
