### PR TITLE
Docker

### LINKED ISSUE #10: Automated Project Registration
Currently, adding your project to the showcase is too much work and makes it hard for users to contribute. To fix this, we need to create a registration form which can collect the required information from an user, and then had his / her project to the showcase with all the details.

### PR DESCRIPTION
**Pull request by Bashamega**
## Fixes Issue

fixes #10 

## Check List (Check all the applicable boxes) 

- [x] My Changes follow the Code of Conduct of this Project. 
- [x] My Post or Change does not contain any **Plagarized** Content. 
- [x] The title of the PR is a short description of the Changes made.

### CODE REVIEW

**Comment by Bashamega** [comment]
Hello @Zemerik 

I have integrated docker and pg and prisma and it works well locally. Note: the api is not very secure. I don't know how to make it secure. I recommend you to make sure that it is secure if you have time.

I hope you like it ❤️

**Comment by Zemerik** [comment]
Hey @Bashamega , 

Thanks for opening a Pull - Request, but there is a slight issue as projects are not able to be fetched properly not allowing users to view any projects. 

By any chance, can you fix this issue?

Screenshot


Regards, 
Zemerik

**Comment by Bashamega** [comment]
> Hey @Bashamega ,
> 
> Thanks for opening a Pull - Request, but there is a slight issue as projects are not able to be fetched properly not allowing users to view any projects.
> 
> By any chance, can you fix this issue?
> 
> Screenshot
> 
> Regards, Zemerik

This is occurring because vercel doesn't support docker you need to see how to host your docker container / pg first. You can test it locally by cloning my branch and running these commands:
 1. Install deps
 ```
npm install
```
2. Setup the docker container (make sure you have docker desktop running):
```
npm run docker:compose
```
3. Generate prisma:
```
npx prisma generate
```
4. Sync your db:
```
npx prisma db push
```
5. Run your development server:
```
npm run dev
```
Then visit your website

**Comment by Zemerik** [comment]
Thanks @Bashamega , 

I will merge you PR once I find a docker container / pg first.

**Comment by Bashamega** [comment]
> Thanks @Bashamega ,
> 
> I will merge you PR once I find a docker container / pg first.

Your welcome. Did it work locally for you?
Also this article might help you: https://medium.com/codex/run-your-docker-containers-for-free-in-the-cloud-and-for-unlimited-time-361515cb0876

**Comment by Zemerik** [comment]
Hey @Bashamega , 

Yes, it worked perfectly fine for me when I locally ran it. Thanks for the Blog link

Regards, 
Zemerik

**Review by Zemerik — APPROVED** [review]

**Comment by Bashamega** [comment]
Dear @Zemerik ,

Did you find a hosting for docker? It doesn't need to support docker but it is important that i has pg. 
I also found that you can run pg on [Vercel](https://vercel.com/docs/storage/vercel-postgres), so you can still be using pg.

If you want help configuring, i can help you:)

Best Regards,
Adam B.

**Pull request closed without merging**
